title: Project
num: '{{ page.created.toDate("Ymd") }}'
status:
  draft:
    label: Unpublished
    text: Page is not published and doesn't appear on the website.
  listed:
    label: Publiziert
    text: Page is published.
options:
  preview: https://aca-rh.net/{{ page.slug }}
  changeTemplate:
    admin: true
    researcher: true
    guest: false
  changeTitle:
    admin: true
    researcher: true
    guest: false
  create:
    admin: true
    researcher: true
    guest: false 
  delete:
    admin: true
    researcher: true
    guest: false
  update:
    admin: true
    researcher: true
    guest: false

tabs:
  homepage:
    label: Metadata
    icon: home
    columns:
      - width: 1/1
        sections:
          homepageA:
            type: fields
            fields:
              title:
                label: Title
                type: markdown
                width: 1/1
              # location:
              #   label: Standort
              #   type: textarea
              #   width: 1/3
              teaser:
                label: Teaser
                type: markdown
                width: 1/1
                maxlength: 400
                buttons:
                  - headlines
                  - bold
                  - italic
                  - link
                  - email
                  - attach
                  - ul
                  - ol
                  - '|'
                  - pagelink
                  - footnote
              description:
                label: Volltext
                type: markdown
                width: 1/1
                buttons:
                  - headlines
                  - bold
                  - italic
                  - link
                  - email
                  - attach
                  - ul
                  - ol
                  - '|'
                  - pagelink
                  - footnote
                  - myextension:
                    pages:
                      query: site.index
                      info: "{{ page.tags }}"
              weiter:
                label: Weiterführende Literatur und Links
                type: structure
                fields:
                  text:
                    label: text
                    type: text
                  url:
                    label: Url
                    type: text
              author:
                label: Autor:innen
                type: structure
                fields:
                  text:
                    label: Autor:in
                    type: text
                  url:
                    label: Url
                    type: text
              categories:
                label: Kategorien
                type: multiselect
                options: query
                query: site.categories.toStructure.pluck("category", ",", true)
                width: 1/2
              tags:
                label: Tags
                type: multiselect
                options: query
                query: site.tags.split
                width: 1/2
              coordinates:
                label: Koordinaten
                type: locator
                width: 1/1
                marker: dark
                center:
                  lat: 50.93381127348
                  lon: 6.95871286291209
                required: false
              line1:
                type: line
              zeit:
                label: Zeit
                type: date
                width: 1/4
                display: YYYY
                required: false
              zeitEnd:
                label: Endzeit
                type: date
                width: 1/4
                display: YYYY
              # identifier:
              #   label: ID
              #   type: number
              #   width: 1/4
  Documents:
    label: Medien
    icon: folder
    columns:
      - width: 1/1
        sections:
          files:
            type: files
            label: Sektion Medien
            layout: cards
            template: image
            accept:
              extension: jpg, png, gif, mp3
